--------------------------------------------------------------------------------
-- NOSSACASA_SORTEIO.CANDIDATO_SORTEIO
--------------------------------------------------------------------------------
ALTER TABLE NOSSACASA_SORTEIO.CANDIDATO_SORTEIO WITH CHECK ADD CONSTRAINT FK_CANDIDATO_SORTEIO_SORTEIO FOREIGN KEY (ID_SORTEIO)
REFERENCES NOSSACASA_SORTEIO.SORTEIO (ID_SORTEIO)
GO
ALTER TABLE NOSSACASA_SORTEIO.CANDIDATO_SORTEIO CHECK CONSTRAINT FK_CANDIDATO_SORTEIO_SORTEIO
GO

ALTER TABLE NOSSACASA_SORTEIO.CANDIDATO_SORTEIO ADD CONSTRAINT DF_CANDIDATO_SORTEIO_CONTEMPLADO DEFAULT (0) FOR CONTEMPLADO
GO

--------------------------------------------------------------------------------
-- NOSSACASA_SORTEIO.CANDIDATO_SORTEIO_LISTA_SORTEIO
--------------------------------------------------------------------------------
ALTER TABLE NOSSACASA_SORTEIO.CANDIDATO_SORTEIO_LISTA_SORTEIO WITH CHECK ADD CONSTRAINT FK_CANDIDATO_SORTEIO_LISTA_SORTEIO_CANDIDATO_SORTEIO FOREIGN KEY (ID_CANDIDATO_SORTEIO)
REFERENCES NOSSACASA_SORTEIO.CANDIDATO_SORTEIO (ID_CANDIDATO_SORTEIO)
GO
ALTER TABLE NOSSACASA_SORTEIO.CANDIDATO_SORTEIO_LISTA_SORTEIO CHECK CONSTRAINT FK_CANDIDATO_SORTEIO_LISTA_SORTEIO_CANDIDATO_SORTEIO
GO

ALTER TABLE NOSSACASA_SORTEIO.CANDIDATO_SORTEIO_LISTA_SORTEIO WITH CHECK ADD CONSTRAINT FK_CANDIDATO_SORTEIO_LISTA_SORTEIO_LISTA_SORTEIO FOREIGN KEY (ID_LISTA_SORTEIO)
REFERENCES NOSSACASA_SORTEIO.LISTA_SORTEIO(ID_LISTA_SORTEIO)
GO
ALTER TABLE NOSSACASA_SORTEIO.CANDIDATO_SORTEIO_LISTA_SORTEIO CHECK CONSTRAINT FK_CANDIDATO_SORTEIO_LISTA_SORTEIO_LISTA_SORTEIO
GO

--------------------------------------------------------------------------------
-- NOSSACASA_SORTEIO.LISTA_SORTEIO
--------------------------------------------------------------------------------
ALTER TABLE NOSSACASA_SORTEIO.LISTA_SORTEIO WITH CHECK ADD CONSTRAINT FK_LISTA_SORTEIO_SORTEIO FOREIGN KEY (ID_SORTEIO)
REFERENCES NOSSACASA_SORTEIO.SORTEIO (ID_SORTEIO)
GO
ALTER TABLE NOSSACASA_SORTEIO.LISTA_SORTEIO CHECK CONSTRAINT FK_LISTA_SORTEIO_SORTEIO
GO

--------------------------------------------------------------------------------
-- NOSSACASA_SORTEIO.EMPREENDIMENTO
--------------------------------------------------------------------------------
ALTER TABLE NOSSACASA_SORTEIO.EMPREENDIMENTO WITH CHECK ADD CONSTRAINT FK_EMPREENDIMENTO_SORTEIO FOREIGN KEY (ID_SORTEIO)
REFERENCES NOSSACASA_SORTEIO.SORTEIO (ID_SORTEIO)
GO
ALTER TABLE NOSSACASA_SORTEIO.EMPREENDIMENTO CHECK CONSTRAINT FK_EMPREENDIMENTO_SORTEIO
GO
